version: '3.8'

services:
  api:
    image: purplewex/homeweb:latest
    ports:
      - "127.0.0.1:5000:8080"

  web:
    image: purplewex/homeweb-client:latest
    ports:
      - "127.0.0.1:5001:80"
    depends_on:
      - api
