name: Deploy CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: Push API image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/homeweb:latest

      - name: Push Client App
        uses: docker/build-push-action@v6
        with:
          context: ./client-app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/homeweb-client:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Read docker-compose
      id: compose
      uses: juliangruber/read-file-action@v1
      with:
        path: ./docker-compose.yml

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          # Log in to DockerHub
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          # Pull the latest images
          docker pull ${{ secrets.DOCKER_USERNAME }}/homeweb:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/homeweb-client:latest

          # Ensure the directory exists
          mkdir -p /web

          # Write the docker-compose.yml file
          echo "${{ steps.compose.outputs.content  }}" > /web/docker-compose.yml

          # Navigate to /web and use Docker Compose
          cd /web
          docker-compose down
          docker-compose up -d


          
