name: Deploy CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
       sparse-checkout: |
        docker-compose

    - name: Read docker-compose.yml
      id: read_file
      run: |
        # Output the contents of docker-compose.yml
        echo "Contents of docker-compose.yml:"
        cat docker-compose.yml
        # Set the contents as an output variable
        echo "::set-output name=file_contents::$(cat docker-compose.yml)"

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          # Log in to DockerHub
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          
          # Ensure the directory exists
          #mkdir -p /web

           echo "${{ steps.read_file.outputs.file_contents }}"



          
