name: Deploy CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: Push API image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/homeweb:latest

      - name: Push Client App
        uses: docker/build-push-action@v6
        with:
          context: ./client-app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/homeweb-client:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Read docker-compose.yml
      id: read_file
      run: |
        file_contents=$(base64 -w 0 docker-compose.yml)
        echo "::set-output name=file_contents::$file_contents"

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          # Log in to DockerHub
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          
          # Ensure the directory exists
          #mkdir -p /web
          
          # Write the content to docker-compose.yml
            echo "${{ steps.read_file.outputs.file_contents }}" | base64 --decode > /web/docker-compose.yml
            docker-compose up -d
